[package]
name = "alt"
version = "0.1.0"
edition = "2021"

description = "Alt Language Executable"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
